### ISSUE TITLE
1234

### ISSUE THREAD

**Issue by lttt123** [nobleo/full_coverage_path_planner#48] opened 2023-11-22 14:51 UTC
Hello, I have now integrated the plugin into Movebase and lowered the frequency to plan a global full coverage path. However, after 3 to 4 rounds, the car will have two goals. This sentence means that it has a goal, and when the car advances towards this goal, the car will have the next goal, and the gap between these two goals is far. The car will move back and forth, causing it to be unable to move. How to solve this problem

**Comment by rokusottervanger** [comment] 2023-11-23 08:57
Closing as a duplicate of #49

**Closed by rokusottervanger** 2023-11-23 08:57 UTC

**Comment by 1234564lll** [comment] 2023-11-23 09:19
> Closing as a duplicate of #49

i don't know what you say

**Comment by rokusottervanger** [comment] 2023-11-23 12:32
This question is the same as the one mentioned in issue 49. I closed this one, so we can continue the discussion in issue 49.
